### ISSUE TITLE
Filling out forms

### ISSUE THREAD

**Issue by Taakn** [pedro-lucas/node-pdfbox#1]
Hello,

I was wondering if your package could fill out forms.

Thanks so much

**Comment by pedro-lucas** [comment]
Hello Taakn,

Could you send to me a pdf to fill out?

I need to a example to use as reference.

**Comment by pedro-lucas** [comment]
I will use the link below to simulate the new feature to the library. 

http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

**Comment by Taakn** [comment]
Hi @pedro-lucas here's a complex example (it's in French):
https://www.formulaires.modernisation.gouv.fr/gf/cerfa_13959.do

You'll notice that some of the trickier parts besides the drop downs and checkboxes that you already have in your document are the COMB fields: the fields that have a set number of characters displayed in adjacent boxes (for example a date or a SSN).

Some of the pdf documents processors out there such as pdftk / pdffiller do not handle a lot of these cases well, so if you manage to get this working that would be fantastic. The other issue is to be able as an option to FLATTEN the document, meaning fill out the form and make it read only. 

Thanks a lot for your help, I can help you test your package.

**Comment by pedro-lucas** [comment]
I'm creating the new classes to manipulate the fields and making new tests.

I think in one week I will submit the new version 0.0.9 with the new features.

### New features
- Fill forms
- Flatten pdf document

**Comment by Taakn** [comment]
That's very cool :)

**Comment by pedro-lucas** [comment]
Please take a look in this file: https://github.com/pedro-lucas/node-pdfbox/blob/development/examples/fill-out-forms/index.js

Try it and give me a feedback please.

**Comment by pedro-lucas** [comment]
You can take this changes in development branch.

**Comment by pedro-lucas** [comment]
Please, check the version 0.0.9.

Thank you!

**Comment by Taakn** [comment]
Hey sorry I've been putting code through production and I've been running into a bunch of issues so unfortunately dealing with that. I will look at your code as soon as I have some time. Thanks again and sorry for the delay in replying to your messages!
