### ISSUE TITLE
Recurso novo

### ISSUE THREAD

**Issue by ghost** [pedro-lucas/node-pdfbox#2]
Será que poderias colocar um método para imprimir o PDF?
Seria perfeito.

**Comment by pedro-lucas** [comment]
Para impressão, você poderia usar um módulo já existente, não sei se este recurso está dentro do escopo do módulo. 

Print: https://www.npmjs.com/package/printer

Caso você realmente precise dessa funcionalidade no módulo, me avise que eu disponibilizo um método para isso.

Obrigado!

**Comment by pedro-lucas** [comment]
Finalizado por falta de novas informações
